### ISSUE TITLE
运行一段时间后无法正常使用

### ISSUE THREAD

**Issue by PumpkinSin** [HaujetZhao/CapsWriter-Offline#14]
报错如下
```
Task exception was never retrieved
future: <Task finished name='Task-14' coro=<do_recognize() done, defined at F:\TEMP\CapsWriter\core_client.py:290>
exception=ValueError('need at least one array to concatenate')>
Traceback (most recent call last):
  File "F:\TEMP\CapsWriter\core_client.py", line 314, in do_recognize
    samples0 = np.concatenate(samples0)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: need at least one array to concatenate
Exception in thread Thread-2 (record):
Traceback (most recent call last):
  File "F:\TEMP\CapsWriter\libs\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "F:\TEMP\CapsWriter\libs\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "F:\TEMP\CapsWriter\core_client.py", line 437, in record
    data = stream.read(int(0.05 * 48000))[0]
  File "F:\TEMP\CapsWriter\libs\sounddevice.py", line 1456, in read
    data, overflowed = RawInputStream.read(self, frames)
  File "F:\TEMP\CapsWriter\libs\sounddevice.py", line 1236, in read
    _check(err)
  File "F:\TEMP\CapsWriter\libs\sounddevice.py", line 2745, in _check
    raise PortAudioError(errormsg, err, hosterror_info)
sounddevice.PortAudioError: Unanticipated host error [PaErrorCode -9999]: 'There is no driver installed on your system.' [MME error 6]
检测到配置文件更新，已载入     4 条中文热词

Task exception was never retrieved
future: <Task finished name='Task-16' coro=<do_recognize() done, defined at F:\TEMP\CapsWriter\core_client.py:290>
exception=ValueError('need at least one array to concatenate')>
Traceback (most recent call last):
  File "F:\TEMP\CapsWriter\core_client.py", line 314, in do_recognize
    samples0 = np.concatenate(samples0)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: need at least one array to concatenate
Task exception was never retrieved
future: <Task finished name='Task-18' coro=<do_recognize() done, defined at F:\TEMP\CapsWriter\core_client.py:290>
exception=ValueError('need at least one array to concatenate')>
Traceback (most recent call last):
  File "F:\TEMP\CapsWriter\core_client.py", line 314, in do_recognize
    samples0 = np.concatenate(samples0)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: need at least one array to concatenate
```

**Comment by HaujetZhao** [comment]
用新版试下
