### ISSUE TITLE
正常使用几小时后出现错误，需要重新打开才能使用，麦克风是正常的，而且最近频繁的出现

### ISSUE THREAD

**Issue by ShiTieSeng** [HaujetZhao/CapsWriter-Offline#16]
Exception in thread Thread-2 (record):
Traceback (most recent call last):
  File "D:\YuYinShuRu\CapsWriter-Offline-Win10-64-Pyinstaller-Without-Models\libs\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "D:\YuYinShuRu\CapsWriter-Offline-Win10-64-Pyinstaller-Without-Models\libs\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\YuYinShuRu\CapsWriter-Offline-Win10-64-Pyinstaller-Without-Models\core_client.py", line 437, in record
    data = stream.read(int(0.05 * 48000))[0]
  File "D:\YuYinShuRu\CapsWriter-Offline-Win10-64-Pyinstaller-Without-Models\libs\sounddevice.py", line 1456, in read
    data, overflowed = RawInputStream.read(self, frames)
  File "D:\YuYinShuRu\CapsWriter-Offline-Win10-64-Pyinstaller-Without-Models\libs\sounddevice.py", line 1236, in read
    _check(err)
  File "D:\YuYinShuRu\CapsWriter-Offline-Win10-64-Pyinstaller-Without-Models\libs\sounddevice.py", line 2745, in _check
    raise PortAudioError(errormsg, err, hosterror_info)
sounddevice.PortAudioError: Unanticipated host error [PaErrorCode -9999]: 'There is no driver installed on your system.' [MME error 6]

**Comment by HaujetZhao** [comment]
用新版试下

**Comment by Eyion** [comment]
使用目前最新版（版本号没有），有以下问题：
1.服务端和客户端共2个窗口，而且不能最小化到任务栏（右下角）？
2.打开双端正常使用，当关闭客户端，此时连接断开，再打开客户端，不会自动重新连接？
3.如何提高说话时断句的识别（即在需要断句时加入标点符号）？

**Comment by HaujetZhao** [comment]
1. 无法实现，你可以放到虚拟桌面
2. 客户端是自动连接的，只要服务端在线、端口正确、没有防火墙阻挡，就应当能连接成功
3. 无法实现，标点符号是根据文字结果推测的
