### ISSUE TITLE
macos 源码安装时，sudo python3 setup.py install，报错

### ISSUE THREAD

**Issue by sigilzen** [HaujetZhao/CapsWriter-Offline#174]
环境：macos 15.1.1、python3.9.6
run ：sudo python3 setup.py install

---------
                    make -j4 install/strip
                
sh: line 3: cmake: command not found
make: *** No rule to make target `install/strip'.  Stop.
Traceback (most recent call last):
  File "/Users/xxj/Documents/CapsWriter-offline/sherpa-onnx/setup.py", line 62, in <module>
    setuptools.setup(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)

**Comment by sigilzen** [comment]
服务端启动的时候，提示：FileExistsError: The models/punc_ct-transformer_cn-en/config.yaml does not exist.
缺少config.yaml文件。看了一下对应的模型文件夹下，确实没有这个配置文件。请哪位大佬指点一下，感谢！

**Comment by sigilzen** [comment]
重新下载了标点模型后，找到了config.yaml文件，服务端也能启动了。但是客户端仍然连不上服务端。提示： 服务端未连接，无法发送。
<img width="1677" alt="iShot_2024-11-27_11 08 53" src="https://github.com/user-attachments/assets/3511dc5c-16bd-4874-b336-b7ba5469fdac">
<img width="1722" alt="iShot_2024-11-27_11 08 02" src="https://github.com/user-attachments/assets/fc37e826-46ac-495d-b54b-ffb6b3015c2f">

**Comment by sigilzen** [comment]
接上，服务端启动的时候有个提示：
objc[60396]: Class CoreMLExecution is implemented in both /Library/Python/3.9/site-packages/sherpa_onnx-1.10.31-py3.9-macosx-10.9-universal2.egg/sherpa_onnx/lib/libonnxruntime.1.17.1.dylib (0x104448c10) and /Library/Python/3.9/site-packages/onnxruntime/capi/onnxruntime_pybind11_state.so (0x12c0d9258). One of the two will be used. Which one is undefined.

**Comment by sigilzen** [comment]
接上，结束任务后，有提示：
<img width="898" alt="iShot_2024-11-27_11 22 21" src="https://github.com/user-attachments/assets/f30beab5-ad64-407e-8507-01a79cabe6f7">

^C
再见！
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 572, in _do_shutdown
    self.call_soon_threadsafe(future.set_result, None)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 791, in call_soon_threadsafe
    self._check_closed()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 574, in _do_shutdown
    self.call_soon_threadsafe(future.set_exception, ex)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 791, in call_soon_threadsafe
    self._check_closed()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
xxj@XiaoJians-MacBook-Pro CapsWriter-Offline-1.0 % /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by mlinuxs** [comment]
问题解决了吗？我的也是客户端连不上，一直提示超时
