### ISSUE TITLE
win10 系统，运行core_server.py出现错误

### ISSUE THREAD

**Issue by jalihui** [HaujetZhao/CapsWriter-Offline#178]
Traceback (most recent call last):
  File "D:\anaconda3\envs\cW\lib\site-packages\websockets\asyncio\server.py", line 353, in conn_handler
    await connection.handshake(
  File "D:\anaconda3\envs\cW\lib\site-packages\websockets\asyncio\server.py", line 204, in handshake
    raise self.protocol.handshake_exc
  File "D:\anaconda3\envs\cW\lib\site-packages\websockets\server.py", line 134, in accept
    ) = self.process_request(request)
  File "D:\anaconda3\envs\cW\lib\site-packages\websockets\server.py", line 279, in process_request
    protocol_header = self.subprotocol = self.process_subprotocol(headers)
  File "D:\anaconda3\envs\cW\lib\site-packages\websockets\server.py", line 419, in process_subprotocol
    return self.select_subprotocol(subprotocols)
  File "D:\anaconda3\envs\cW\lib\site-packages\websockets\server.py", line 467, in select_subprotocol
    raise NegotiationError("missing subprotocol")
websockets.exceptions.NegotiationError: missing subprotocol
opening handshake failed

**Comment by BigYty** [comment]
我在ubutu22.0上同样出现了这个问题，没有找到解决办法

**Comment by RyanShaw-3083** [comment]
Downgrade the version of the Websockets package to 13.0 with `pip install websockets==13.0`. 
- 降级 Websockets 包的版本为 13.0 `pip install websockets==13.0`
