### ISSUE TITLE
win11报错

### ISSUE THREAD

**Issue by wangmw3617** [HaujetZhao/CapsWriter-Offline#35]
C:\Users\wang\AppData\Local\Programs\Python\Python310\lib\site-packages\funasr_onnx\punc_bin.py:
279: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.  
  def vad_mask(self, size, vad_pos, dtype=np.bool):
Process Process-2:                                                                              
Traceback (most recent call last):
  File "C:\Users\wang\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\wang\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "d:\软件工具\python小工具\CapsWriter-Offline\util\server_init_recognizer.py", line 29, in init_recognizer
    from funasr_onnx import CT_Transformer
  File "C:\Users\wang\AppData\Local\Programs\Python\Python310\lib\site-packages\funasr_onnx\__init__.py", line 5, in <module>
    from .punc_bin import CT_Transformer
  File "C:\Users\wang\AppData\Local\Programs\Python\Python310\lib\site-packages\funasr_onnx\punc_bin.py", line 166, in <module>
    class CT_Transformer_VadRealtime(CT_Transformer):
  File "C:\Users\wang\AppData\Local\Programs\Python\Python310\lib\site-packages\funasr_onnx\punc_bin.py", line 279, in CT_Transformer_VadRealtime
    def vad_mask(self, size, vad_pos, dtype=np.bool):
  File "C:\Users\wang\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\__init__.py", line 338, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

**Comment by HaujetZhao** [comment]
改库里的源代码，把 np.bool 改为 bool
