### ISSUE TITLE
打包完运行后缺少库

### ISSUE THREAD

**Issue by wangmw3617** [HaujetZhao/CapsWriter-Offline#36]
绑定的服务地址：0.0.0.0:6016

Process Process-2:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 314, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "D:\软件工具\python小工具\CapsWriter-Offline\dist\CapsWriter-Offline\util\server_init_recognizer.py", line 29, in init_recognizer
    from funasr_onnx import CT_Transformer
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "funasr_onnx\__init__.py", line 2, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "funasr_onnx\paraformer_bin.py", line 10, in <module>
ModuleNotFoundError: No module named 'torch'

打包前正常运行

**Comment by HaujetZhao** [comment]
pip install funasr_onnx==0.2.5
