### ISSUE TITLE
服务端运行报错，试了两台电脑都是一样效果

### ISSUE THREAD

**Issue by coolboy0002001** [HaujetZhao/CapsWriter-Offline#4]
Traceback (most recent call last):
  File "start_server.py", line 10, in <module>
  File "D:\BaiduNetdiskDownload\CapsWriter-Offline-Win10-64-Pyinstaller-Without-Models\core_server.py", line 207, in init
    asyncio.run(main())
  File "D:\BaiduNetdiskDownload\CapsWriter-Offline-Win10-64-Pyinstaller-Without-Models\libs\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\BaiduNetdiskDownload\CapsWriter-Offline-Win10-64-Pyinstaller-Without-Models\libs\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\BaiduNetdiskDownload\CapsWriter-Offline-Win10-64-Pyinstaller-Without-Models\core_server.py", line 170, in main
    recognizer = sherpa_onnx.OfflineRecognizer.from_paraformer(
  File "D:\BaiduNetdiskDownload\CapsWriter-Offline-Win10-64-Pyinstaller-Without-Models\libs\sherpa_onnx\offline_recognizer.py", line 158, in from_paraformer
    self.recognizer = _Recognizer(recognizer_config)
RuntimeError: Failed to load model with error: D:\a\_work\1\s\onnxruntime\core/graph/model_load_utils.h:56 onnxruntime::model_load_utils::ValidateOpsetForDomain ONNX Runtime only *guarantees* support for models stamped with official released onnx opset versions. Opset 19 is under development and support for this is limited. The operator schemas and or other functionality may change before next ONNX release and in this case ONNX Runtime will not guarantee backward compatibility. Current official support for domain com.ms.internal.nhwc is till opset 18.

[8260] Failed to execute script 'start_server' due to unhandled exception!

**Comment by HaujetZhao** [comment]
我借了电脑，更新百度网盘中的 windows 版本了。

**Comment by caiqingzhi2020** [comment]
刚下载过来时候core_client py里面端口是16007,改成了6006就能解决连接不到server这个问题

**Comment by HaujetZhao** [comment]
真是抱歉，忘记端口的小小失误了
