### ISSUE TITLE
Ubuntu22.04下运行core_server.py报错

### ISSUE THREAD

**Issue by BreakMeEveryday** [HaujetZhao/CapsWriter-Offline#47]
`Process Process-2:
Traceback (most recent call last):
  File "/home/programmer/.conda/envs/capswriter/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()

  File "/home/programmer/.conda/envs/capswriter/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)

  File "/home/programmer/Projects/PycharmProjects/CapsWriter-Offline/util/server_init_recognizer.py", line 35, in init_recognizer
    recognizer = sherpa_onnx.OfflineRecognizer.from_paraformer(

  File "/home/programmer/.conda/envs/capswriter/lib/python3.8/site-packages/sherpa_onnx/offline_recognizer.py", line 184, in from_paraformer
    self.recognizer = _Recognizer(recognizer_config)

RuntimeError: Failed to load model because protobuf parsing failed.
`
Python=3.8，依赖确认均安装到位，models目录下的两份模型文件也具备，无英伟达显卡，无CUDA

**Comment by HaujetZhao** [comment]
这是语音模型加载出了问题

1. 首先，确保模型文件是从 releases 界面或者百度网盘下载打包的，直接可用。因为 modelscope 下载的模型需要加工一下。
2. 确保 sherpa-onnx 安装正确。可以尝试升级看下 pip install -U sherpa-onnx

**Comment by cancundeyingzi** [comment]
用win版就行了,Linux也能用
