### ISSUE TITLE
Win10 server端运行错误

### ISSUE THREAD

**Issue by feijie825** [HaujetZhao/CapsWriter-Offline#61]
运行start_server.exe时报错。
```
Process Process-2:
Traceback (most recent call last):
  File "jieba\__init__.py", line 78, in gen_pfdict
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xab in position 16: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "E:\Portable\CapsWriter-Offline-Windows-64bit\util\server_init_recognizer.py", line 44, in init_recognizer
    punc_model = CT_Transformer(ModelPaths.punc_model_dir, quantize=True)
  File "funasr_onnx\punc_bin.py", line 83, in __init__
  File "funasr_onnx\utils\utils.py", line 302, in code_mix_split_words_jieba
  File "jieba\__init__.py", line 395, in load_userdict
  File "jieba\__init__.py", line 170, in check_initialized
  File "jieba\__init__.py", line 145, in initialize
  File "jieba\__init__.py", line 88, in gen_pfdict
ValueError: invalid dictionary entry in <_io.BytesIO object at 0x0000020908886F40> at Line 1: b'%TSD-Header-###%\xab\x05\x9d\x05\x8a\xd3^N\x95\xb2V\xcb\x80\x8d)8\x01\x00\x04\x00H\x00\x00\x00\x00\x00\x00\x00\x06D\xff\xff@\x00\x01\x00\xd9\x1f+\x1du\x86\x00\x00/\xc0P\x00$\xc9i\xb1\x96\xb6~Y\x12\xb0\xf9\x08y\x02\xbfM\x88D\xcc\xa5\x18p6\xc06\n'
```
![image](https://github.com/HaujetZhao/CapsWriter-Offline/assets/19851253/d16625b7-e701-40c8-8282-a6383a786dbf)

![image](https://github.com/HaujetZhao/CapsWriter-Offline/assets/19851253/853c7796-a813-4724-9dbd-2e22f7e79f93)

**Comment by A-FK369** [comment]
![1710955207679](https://github.com/HaujetZhao/CapsWriter-Offline/assets/115731209/8bae5f89-09b4-4a4a-9054-19498b28769e)
