### ISSUE TITLE
[bug]: 服务端启动报错

### ISSUE THREAD

**Issue by UlinoyaPed** [HaujetZhao/CapsWriter-Offline#95]
<details><summary>Details</summary>
<div>

Process Process-2:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "D:\Tools\CapsWriter\CapsWriter-Offline-Windows-64bit\util\server_init_recognizer.py", line 44, in init_recognizer
    punc_model = CT_Transformer(ModelPaths.punc_model_dir, quantize=True)
  File "funasr_onnx\punc_bin.py", line 69, in __init__
  File "funasr_onnx\utils\utils.py", line 209, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 452, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from models\punc_ct-transformer_cn-en\model_quant.onnx failed:bad allocation

</div>
</details> 

## 描述Bug *Describe the bug*

服务端启动时报错，报错信息如下

```
Process Process-2:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "D:\Tools\CapsWriter\CapsWriter-Offline-Windows-64bit\util\server_init_recognizer.py", line 44, in init_recognizer
    punc_model = CT_Transformer(ModelPaths.punc_model_dir, quantize=True)
  File "funasr_onnx\punc_bin.py", line 69, in __init__
  File "funasr_onnx\utils\utils.py", line 209, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 452, in _create_inference_session
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from models\punc_ct-transformer_cn-en\model_quant.onnx failed:bad allocation
```

## 如何再现 *To Reproduce*

再现Bug的步骤：
1. models已下载并复制到models文件夹
1. 双击`start_server.exe`启动服务端，模块成功加载，语音模块成功加载
1. 标点模型等待较长时间后加载失败并显示报错，多次尝试结果相同

## 截屏 *Screenshots*

![image](https://github.com/HaujetZhao/CapsWriter-Offline/assets/107659010/49f494b3-8685-42c5-8bf6-0154652c0b34)
/

## 出现问题的设备 *Devices with issues*

- 设备：Win10 20H2
- 软件&版本：v1.0

## 备注 *Additional context*

`models/模型测试`文件夹中的python文件也不能正常运行

```
D:\Tools\CapsWriter\CapsWriter-Offline-Windows-64bit\models\模型测试>python D:\Tools\CapsWriter\CapsWriter-Offline-Windows-64bit\models\模型测试\03-01-标点模型测试.py
Traceback (most recent call last):
  File "D:\Tools\CapsWriter\CapsWriter-Offline-Windows-64bit\models\模型测试\03-01-标点模型测试.py", line 1, in <module>
    from funasr_onnx import CT_Transformer
ModuleNotFoundError: No module named 'funasr_onnx'
```

**Comment by gongqf** [comment]
03-01-标点模型测试.py 要复制到模型文件夹下才能运行

**Comment by HaujetZhao** [comment]
`03-01-标点模型测试.py` 复制到标点模型文件夹内运行测试下

**Comment by HaujetZhao** [comment]
bad allocation ，有可能是内存不足导致。

你的电脑内存多大，设置的虚拟内存多大？

**Comment by UlinoyaPed** [comment]
> bad allocation ，有可能是内存不足导致。
> 
> 你的电脑内存多大，设置的虚拟内存多大？

🤔 可能是这个原因，我电脑内存只有4G，虚拟内存也不太大。

不过[mem reduct](https://github.com/henrypp/memreduct)在过程中全程开启，系统空载时其内存占用显示为40%, 整个运行过程中显示的内存占用一直未超过60%. 如果是内存不够为什么不会把内存占满？

**Comment by HaujetZhao** [comment]
虚拟内存放大到 16G

**Comment by qsxmj** [comment]
Process Process-2:
Traceback (most recent call last):
  File "multiprocessing\process.py", line 315, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "D:\Ai\CapsWriter-Offline-Windows-64bit-withmodles\util\server_init_recognizer.py", line 44, in init_recognizer
    punc_model = CT_Transformer(ModelPaths.punc_model_dir, quantize=True)
  File "funasr_onnx\punc_bin.py", line 83, in __init__
  File "funasr_onnx\utils\utils.py", line 302, in code_mix_split_words_jieba
  File "jieba\__init__.py", line 416, in load_userdict
  File "jieba\__init__.py", line 427, in add_word
  File "jieba\__init__.py", line 464, in suggest_freq
ZeroDivisionError: float division by zero
这是我遇到的报错 与你复现经历的相似
